# ===================================
#  List Behavior Config
# ===================================

title: backend::lang.user.list_title
list: ~/modules/backend/models/catgeventos/columns.yaml
modelClass: Backend\Models\Catgeventos
recordUrl: backend/catgeventos/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
# showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt