# ===================================
#  Form Behavior Config
# ===================================

name: Tipo de empresa
form: ~/modules/backend/models/tipo/fields.yaml
modelClass: Backend\Models\Tipo
defaultRedirect: backend/tipo

create:
    redirect: backend/tipo/update/:id
    redirectClose: backend/tipo

update:
    redirect: backend/tipo
    redirectClose: backend/tipo
