# ===================================
#  Form Behavior Config
# ===================================

name: Empresa
form: ~/modules/backend/models/empresa/fields.yaml
modelClass: Backend\Models\Empresa
defaultRedirect: backend/empresa

create:
    redirect: backend/empresa/update/:id
    redirectClose: backend/empresa

update:
    redirect: backend/empresa
    redirectClose: backend/empresa
