# ===================================
#  Form Behavior Config
# ===================================

name: Home
form: ~/modules/backend/models/home/fields.yaml
modelClass: Backend\Models\Home
defaultRedirect: backend/home

create:
    redirect: backend/homes/update/:id
    redirectClose: backend/home

update:
    redirect: backend/homes
    redirectClose: backend/home
